# Generated by Django 6.1 on 2026-08-18 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_group_password_hash_expense_expensesplit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('created_by', 'name')},
        ),
    ]
